#pragma once
#include <Arduino.h>

enum ESP32_Pins : uint8_t {
  // ---- GPIO ----
  GPIO0,   // TOUCH1, ADC11, PIN_UART0_TX, cuidado: pin de arranque
  GPIO1,   // PIN_UART0_TX (depuración serie)
  GPIO2,   // TOUCH2, ADC12
  GPIO3,   // PIN_UART0_RX (depuración serie)
  GPIO4,   // TOUCH0, ADC10
  GPIO5,   // VSPI_SS
  GPIO6,   // PIN_FLASH_CK
  GPIO7,   // PIN_FLASH_D0
  GPIO8,   // PIN_FLASH_D1
  GPIO9,   // PIN_UART1_RX, PIN_FLASH_D2
  GPIO10,  // PIN_UART1_TX, PIN_FLASH_D3
  GPIO12 = 12, // TOUCH5, ADC15
  GPIO13,  // TOUCH4, ADC14
  GPIO14,  // TOUCH6, ADC16
  GPIO15,  // TOUCH3, ADC13
  GPIO16,  // PIN_UART2_RX
  GPIO17,  // PIN_UART2_TX
  GPIO18,  // VSPI_SCK
  GPIO19,  // VSPI_MISO
  GPIO21 = 21, // I2C_SDA
  GPIO22,  // I2C_SCL
  GPIO23,  // VSPI_MOSI
  GPIO25 = 25, // ADC18, DAC1, usado como PIN_DAC1
  GPIO26,  // ADC19, DAC2, usado como PIN_DAC2
  GPIO27,  // TOUCH7, ADC17
  GPIO32 = 32, // TOUCH9, ADC4
  GPIO33,  // TOUCH8, ADC5
  GPIO34,  // INPUT ONLY, ADC6
  GPIO35,  // INPUT ONLY, ADC7
  GPIO36,  // INPUT ONLY, ADC0, VP
  GPIO39 = 39,  // INPUT ONLY, ADC3, VN

  // ---- INPUT ONLY ----
  PIN_INPUT_ONLY_0 = GPIO34,
  PIN_INPUT_ONLY_1 = GPIO35,
  PIN_INPUT_ONLY_2 = GPIO36,
  PIN_INPUT_ONLY_3 = GPIO39,

  // ---- DAC ----
  PIN_DAC0 = GPIO25,
  PIN_DAC1 = GPIO26,

  // ---- TOUCH ----
  PIN_TOUCH0 = GPIO4,  
  PIN_TOUCH1 = GPIO0,  
  PIN_TOUCH2 = GPIO2,  
  PIN_TOUCH3 = GPIO15, 
  PIN_TOUCH4 = GPIO13, 
  PIN_TOUCH5 = GPIO12, 
  PIN_TOUCH6 = GPIO14, 
  PIN_TOUCH7 = GPIO27, 
  PIN_TOUCH8 = GPIO33, 
  PIN_TOUCH9 = GPIO32, 

  // ---- UART ----
  PIN_UART0_TX = GPIO1,
  PIN_UART0_RX = GPIO3,
  PIN_UART1_TX = GPIO10,
  PIN_UART1_RX = GPIO9,
  PIN_UART2_TX = GPIO17,
  PIN_UART2_RX = GPIO16,

  // ---- I2C ----
  PIN_I2C_SDA = GPIO21,
  PIN_I2C_SCL = GPIO22,

  // ---- SPI (VSPI por defecto) ----
  PIN_VSPI_MOSI = GPIO23,
  PIN_VSPI_MISO = GPIO19,
  PIN_VSPI_SCK  = GPIO18,
  PIN_VSPI_SS   = GPIO5,

  // ---- Pines reservados para Flash (NO usar) ----
  PIN_FLASH_CK  = GPIO6, 
  PIN_FLASH_D0  = GPIO7, 
  PIN_FLASH_D1  = GPIO8, 
  PIN_FLASH_D2  = GPIO9, 
  PIN_FLASH_D3  = GPIO10
};

enum : uint8_t {
  // --- Caudalímetros (entradas con interrupción) ---
  PIN_CAUD_0        = PIN_TOUCH9,
  PIN_CAUD_1        = PIN_TOUCH8,
  PIN_CAUD_2        = PIN_INPUT_ONLY_0,

  // --- Ultrasonidos: TRIG = salida, ECHO = entrada ---
  PIN_ULTRA_TRIG_0  = PIN_DAC0,
  PIN_ULTRA_ECHO_0  = PIN_INPUT_ONLY_1,

  PIN_ULTRA_TRIG_1  = PIN_DAC1,
  PIN_ULTRA_ECHO_1  = PIN_INPUT_ONLY_2,

  PIN_ULTRA_TRIG_2  = PIN_UART2_RX,
  PIN_ULTRA_ECHO_2  = PIN_INPUT_ONLY_3,

  // --- Actuadores (salidas) ---
  PIN_COMPUERTA     = PIN_TOUCH4,
  PIN_ACTUADOR_DIGITAL_0  = PIN_TOUCH5,
  PIN_ACTUADOR_DIGITAL_1  = PIN_TOUCH6,
  PIN_ACTUADOR_DIGITAL_2  = PIN_UART2_TX,

  // --- Pulsadores (puedes leerlos como digitales o usar touch) ---
  PIN_PULSADOR_0    = PIN_TOUCH0,
  PIN_PULSADOR_1    = PIN_TOUCH2,
  PIN_PULSADOR_2    = PIN_TOUCH3,
  PIN_PULSADOR_3    = PIN_TOUCH7,

  // --- Pantalla TFT ILI9341 (SPI) ---
  PIN_TFT_CS   = PIN_VSPI_SS,
  PIN_TFT_DC   = PIN_I2C_SDA,
  PIN_TFT_RST  = PIN_I2C_SCL
};
